### ISSUE TITLE
Error : SyntaxError

### ISSUE THREAD

**Issue by bhabotta9** [jadhavpritish/Dream11_Predictor#2]
File "player_selection_dream11.py", line 53
    def read_data(abs_filename: str) -> pd.DataFrame:
                             ^
SyntaxError: mismatched input ':' expecting RPAREN

**Comment by pritishperpetua** [comment]
@bhabotta9  - can you copy-paste the command that you are using for running the script?

**Comment by bhabotta9** [comment]
![image](https://user-images.githubusercontent.com/33625756/93973362-b3fcdd00-fd91-11ea-938f-70ccc614545c.png)

**Comment by jadhavpritish** [comment]
I would highly recommend you to use pipenv because it will help you setup the correct environment inclu python version. 

You can find the steps in the README.

For convenience - 
1. install [pipenv](https://pypi.org/project/pipenv/) 
2. run `pipenv install --dev`
3. run `pipenv run python src/player_selection_dream11.py--player_data_filepath <absolute_data_filepath>`

Hope this helps.
